my_gripper:
  # publish all joint states --------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers -----------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 10000.0, i: 0.01, d: 200.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 25.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 120.0, i: 0.01, d: 30.0}
  gripper_base_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_l_finger_controller:
    type: effort_controllers/JointPositionController
    joint: l_gripper_l_finger_joint
    pid: {p: 1000,  i: 0.1, d: 10}
  gripper_r_finger_controller:
    type: effort_controllers/JointPositionController
    joint: l_gripper_r_finger_joint
    pid: {p: 1000,  i: 0.1, d: 10}
